version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest # SQL Server 2019 イメージでビルド
    ports:
      - 11433:1433 # Azure Data Studio など外部から接続するときはサーバーに「localhost, 11433」を指定する
    environment:
      - ACCEPT_EULA=Y                    # EULA（使用許諾契約）に同意する ※起動にはこの設定が必須
      - MSSQL_PID=Express                # Express エディション（ライセンスが不要）を使用
      - MSSQL_AGENT_ENABLED=true         # SQLServer を落とさずに起動し続ける
      - PATH=$PATH:/opt/mssql-tools/bin/ # sqlcmd の PATH を通す
      - SA_PASSWORD                      # .env からパスワードを渡す
      - TZ=Asia/Tokyo                    # タイムゾーンを JST で設定
    volumes:
      - ./mount_dir:/mount_dir    # ホストディレクトリ:コンテナディレクトリ でバインドマウント。./mount_dir ディレクトリ配下にファイルを配置すると、コンテナ上の root 配下にある同名ディレクトリへファイルが同期される
      - db-volume:/var/opt/mssql/ # 名前付きデータボリューム:コンテナディレクトリ でバインドマウント。db-volume データボリュームとコンテナの MSSQL ディレクトリをマウントし、データを永続化する

# 利用するボリュームの定義
volumes:
  db-volume: # 永続化のためにマウントするデータボリュームの名前を定義。
