version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 11433:1433
    environment:
      - ACCEPT_EULA=Y                    # EULA（使用許諾契約）に同意
      - MSSQL_SA_PASSWORD                # MSSQL のパスワード。.env に記述されたパスワードを渡す
      - MSSQL_PID=Express                # Express エディションを使用
      - MSSQL_AGENT_ENABLED=true         # SQLServer を落とさずに起動し続ける
      - PATH=$PATH:/opt/mssql-tools/bin/ # sqlcmd の PATH を通す
      - TZ=Asia/Tokyo                    # タイムゾーンを JST で設定
    volumes:
      - ./mount_dir:/mount_dir    # ホストディレクトリ:コンテナディレクトリ でバインドマウント。./mount_dir ディレクトリ配下にファイルを配置すると、コンテナ上の root 配下にある同名ディレクトリへファイルが同期される
      - db-volume:/var/opt/mssql/ # 名前付きデータボリューム:コンテナディレクトリ でバインドマウント。db-volume データボリュームとコンテナの MSSQL ディレクトリをマウントし、データを永続化する
volumes:
  db-volume: # データボリュームの名前を定義
